---
title: "Cell Viability"
author: "Samuel Gurr"
date: "2025-06-26"
output: html_notebook
---

-   Last updates: 7/10/25

# OAP flow cytometry analysis

## Load Libraries

```{r set up, include=FALSE}

library(lmtest) # to receive p value from betareg model
library(FSA) # for the Dun test post hoc for SRH non-parametric 2 way anova]
library(emmeans)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(car)
library(lmerTest)
library(tidyr)
library(tidyverse)
library(reshape2)
library(ggpubr)
library(nlme)
library(rcompanion) # to run the Schrier -Ray-Hare non parametric 2 way 
knitr::opts_knit$set(root.dir = "C:/Users/samjg/Documents/Github_repositories/Pmagellanicus_omics/RAnalysis") # sets the working directory for the entire R markdown file - no need to reload the wd
```

## Load flow cytometry data

**NOTE**: the statistics option ion C6 PLus software was used to compile the data (i.e. mean FL1) - the following loaded data file was assembled manually to include the sample metadata (i.e. data, treatments, etc.) as well as these flow cytometry data

```{r load data}
# getwd()
# read data 
data  <- read.csv(file="C:/Users/samjg/Documents/Github_repositories/Pmagellanicus_omics/RAnalysis/Data/Flow_cytometry/Cell_viability_raw.csv", header = TRUE)  %>% 
              # dplyr::select(-c(X)) %>% 
              dplyr::mutate(Proportion_alive_ADJ = (Live/(Live+Dead))) %>% 
              dplyr::mutate(Proportion_dead_ADJ = (Dead/(Live+Dead))) 
data <- data[-1,] # omit row one, sampled 1 was redone 
# View(data)

treatment_metadata <- read.csv(file="C:/Users/samjg/Documents/Github_repositories/Pmagellanicus_omics/RAnalysis/Data/Experiment_metadata/Experiment_metadata.csv", header = TRUE) %>% dplyr::select(c(Tank_num, Temperature, OA, Color))
  
sample_metadata    <- read.csv(file="C:/Users/samjg/Documents/Github_repositories/Pmagellanicus_omics/RAnalysis/Data/Experiment_metadata/Sample_metadata.csv", header = TRUE) %>% dplyr::select(-c(TagSeq_ID, ATACseq_ID))

metadata <- merge(treatment_metadata, sample_metadata) 
metadata %>% group_by(OA, Temperature, Tag_color) %>% summarise(n = n())

final <- merge(data, metadata, by = "flow_cy_ID") %>% 
          dplyr::select(Date, Day, 
                        Tank_num, Color, Tag_color,
                        Temperature, OA,
                        flow_cy_ID, Proportion_alive_ADJ) %>% 
          dplyr::mutate(population = 
                       case_when(Tag_color %in% 'blue' ~ 'Cobscook',
                                 TRUE ~ 'Hurricane')) %>% 
          dplyr::mutate(treatment =
                          paste0(Temperature,'_X_', OA))

final_OM <- final %>% # data %>%
  # dplyr::filter(!flow_cy_ID %in% c(3,8,11,18,21,27)) %>%
  # dplyr::filter(!(population %in% 'Hurricane' & Proportion_alive_ADJ < 0.18)) %>% 
  dplyr::mutate(OA_Pop = paste0(OA,"_",population),
                Arag  = case_when(
                  (Temperature %in% 'High' & OA %in% 'Low') ~ 1,
                  (Temperature %in% 'Low' & OA %in% 'Low') ~ 2,
                  (Temperature %in% 'High' & OA %in% 'High') ~ 3,
                  (Temperature %in% 'Low' & OA %in% 'High') ~ 4))

final_OM %>% group_by(population,OA,Temperature) %>% dplyr::summarise(n=n())
```


```{r visualize data}
    

# Calculate summary statistics per group
ggplot(final_OM, aes(x = factor(Temperature), y = Proportion_alive_ADJ, group=population)) +
  geom_jitter(alpha = 0.5, size = 2, position=position_dodge(.4)) +
  # Add mean and error bar (standard error)
  stat_summary(fun = mean, geom = "point", size = 2, color = "red",position=position_dodge(.4)) +
  stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.2, color = "red", position=position_dodge(.4)) +
  scale_shape_manual(values=c(21, 22)) + # filled circle, filled triangle, and X 
  scale_fill_manual(values = c("#009E73", "#CC79A7")) +
    # geom_jitter() +
    theme_classic() +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
    ggtitle("Percent alive cells - 14 days") +
    labs(y= "Percent alive cells (%)", x = "Temperature") +
    facet_wrap(~OA)
# summary
summary_df <- final_OM %>% # data %>%
  # edit data to suit out needs
  group_by(Temperature, OA, treatment, population) %>% # group by columns for treatment
  dplyr::summarise( # summarise to aquire the mean and SE for plotting
    PercLive_mean = mean(Proportion_alive_ADJ), # mean
    PercLive_sd = sd(Proportion_alive_ADJ), # sd
    n = n(), # count
    PercLive_se = PercLive_sd / sqrt(n)) # SE

# plot it
PropLive_RxnNorm <- 
  ggplot(final_OM, aes(x=Temperature, y=Proportion_alive_ADJ, group=OA)) + 
    #geom_line(aes(group = factor(population), linetype = population), size = 0.5, position=position_dodge(.4)) +  # connect a line between variables
    #scale_linetype_manual(values=c("solid", "dashed")) +
    # geom_point(aes(shape=OA, fill=OA), size = 4,position=position_dodge(.4)) + 
    geom_jitter(width = 0.15, alpha = 0.5, size = 2) + # all data points
    geom_point(data = summary_df, aes(x = Temperature, 
                                      y = PercLive_mean,
                                      shape=OA, 
                                      fill=OA), 
               size = 4,
               position=position_dodge(.4)) + 
    scale_shape_manual(values=c(21, 22)) + # filled circle, filled triangle, and X 
    scale_fill_manual(values = c("#009E73", "#CC79A7")) +
    geom_errorbar(data = summary_df, aes(x = Temperature,
                                         y = PercLive_mean,
                                         ymin=(PercLive_mean)-(PercLive_se), 
                                         ymax=(PercLive_mean)+(PercLive_se)), 
                  width=.2,
                  position=position_dodge(.4)) +
    # geom_jitter() +
    theme_classic() +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
    ggtitle("Percent alive cells - 14 days") +
    labs(y= "Percent alive cells (%)", x = "Temperature") +
    facet_wrap(~population)
PropLive_RxnNorm

View(final_OM)
# Mean SE

final_OM$treatment <- factor(final_OM$treatment, 
                             levels=c("High_X_Low", "Low_X_Low", "High_X_High", "Low_X_High"))
PropLive_RxnNorm <- final_OM %>% 
                    dplyr::mutate(Proportion_dead_ADJ = 1-Proportion_alive_ADJ) %>% 
                    # dplyr::filter(!(population %in% 'Hurricane' & Proportion_alive_ADJ < 0.18)) %>%
                    dplyr::filter(!Proportion_alive_ADJ < 0.18) %>% 
                       ggplot(
                       aes(x=treatment,
                           y=as.numeric(Proportion_alive_ADJ),
                           group=factor(OA_Pop)), 
                       stat="identity") +
                       geom_point(position = position_dodge2(width = 0.2)) + 
                       stat_summary(fun.y="mean", size = 0.8,
                                          position = position_dodge2(width = 0.2),
                                    color=c("black", "grey40",
                                            "black", "grey40",
                                            "black", "grey40",
                                            "black", "grey40"),
                                    shape=c(19,19,
                                            19,19,
                                            19,19,
                                            19,19)) +
                       stat_summary(fun.min = function(x) mean(x) - sd(x)/sqrt(length(x)), 
                                          fun.max = function(x) mean(x) + sd(x)/sqrt(length(x)),
                                          geom = 'errorbar', width = 0.25, size = 1,
                                          position = position_dodge2(width = 0.2),
                                    color=c("black", "grey40",
                                            "black", "grey40",
                                            "black", "grey40",
                                            "black", "grey40")) + 
                        labs(title="Percent alive cells - 14 days", 
                            x ="Treatment", 
                            y = "Percent alive cells (%)") +
                        # scale_fill_manual(breaks=c("Low pCO2", "Moderate pCO2", "High pCO2"), 
                        #                    values=c("forestgreen","orange", "purple")) +
                        # scale_fill_manual(breaks=c("High pCO2", "Low pCO2"), 
                        #                    values=c("#009E73", "#CC79A7")) +
                        # scale_x_discrete(labels=c("L", "M", "H")) +
                        # scale_y_continuous(expand = c(0, 0), limits = c(0, 0.7), breaks = seq(0, 0.7, by = 0.1)) +
                        theme_classic() +
                        theme(panel.grid.major = element_blank(), 
                              panel.grid.minor = element_blank(), 
                              # axis.title.x=element_blank(),
                              axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=1),
                              axis.text=element_text(size=8),
                              plot.title = element_text(size=12),
                              legend.position="none") +
                      facet_wrap(~population)
print(PropLive_RxnNorm)



```



```{r statistics}


TwoWaymod <- aov(
  lm(
    Proportion_alive_ADJ ~
      as.factor(Arag) * population,
    data = final_OM)
  )

shapiro.test(residuals(TwoWaymod))
# data:  residuals(TwoWaymod)
# W = 0.98186, p-value = 0.7581
summary(TwoWaymod)
#                            Df Sum Sq  Mean Sq F value Pr(>F)
# as.factor(Arag)             3 0.0757 0.025219   1.175  0.342
# population                  1 0.0156 0.015647   0.729  0.402
# as.factor(Arag):population  3 0.0270 0.009008   0.420  0.741
# Residuals                  22 0.4721 0.021457 

Cobscook_mod <- lm(
                    Proportion_alive_ADJ ~
                      # OA * Temperature,
                      as.factor(Arag) ,
                    data = (final_OM %>% # data %>%
                              dplyr::filter(population %in% 'Cobscook')))
shapiro.test(resid(Cobscook_mod)) # 0.1339
leveneTest(Cobscook_mod) # 0.2714
summary(Cobscook_mod)
summary(
     aov(
       lm(
          Proportion_alive_ADJ ~
            # OA * Temperature,
            as.factor(Arag),
          data = (final_OM %>% # data %>%
                    dplyr::filter(population %in% 'Cobscook')) #  %>% 
                    # dplyr::filter(!flow_cy_ID %in% c(3,8,27)) %>% 
                    # dplyr::filter(!flow_cy_ID < 16))
         )
        )
       )





Cobscook_Twoway <- lm(
                    Proportion_alive_ADJ ~
                      Temperature * OA,
                    data = (final_OM %>% # data %>%
                    dplyr::filter(population %in% 'Cobscook'))
                      )
shapiro.test(resid(Cobscook_Twoway)) # 0.1339
summary(Cobscook_Twoway)
#                      Estimate Std. Error t value Pr(>|t|)    
# (Intercept)           0.39364    0.07449   5.285 0.000115 ***
# TemperatureLow       -0.05652    0.11173  -0.506 0.620820    
# OALow                 0.06406    0.10534   0.608 0.552842    
# TemperatureLow:OALow -0.06324    0.15801  -0.400 0.695032 

Cobscook_Oneway <- lm(
                    Proportion_alive_ADJ ~
                      treatment,
                    data = (final_OM %>% # data %>%
                    dplyr::filter(population %in% 'Cobscook'))
                      )
shapiro.test(resid(Cobscook_Oneway)) # 0.1339
leveneTest(Cobscook_Oneway) # 0.5247






Hurricane_Twoway <- lm(
                    Proportion_alive_ADJ ~
                      Temperature * OA,
                    data = (final_OM %>% # data %>%
                    dplyr::filter(population %in% 'Hurricane'))
                      )
shapiro.test(resid(Hurricane_Twoway)) # 0.9996
summary(Hurricane_Twoway)
#                      Estimate Std. Error t value Pr(>|t|)    
# (Intercept)           0.41069    0.04573   8.980 1.88e-05 ***
# TemperatureLow       -0.08406    0.08556  -0.982    0.355    
# OALow                -0.04855    0.07468  -0.650    0.534    
# TemperatureLow:OALow -0.07617    0.12663  -0.602    0.564 

Hurricane_Oneway <- lm(
                    Proportion_alive_ADJ ~
                      treatment,
                    data = (final_OM %>% # data %>%
                    dplyr::filter(population %in% 'Hurricane'))
                      )
shapiro.test(resid(Hurricane_Oneway)) # 0.9996
leveneTest(Hurricane_Oneway) # 0.708
summary(Hurricane_Oneway)
#                     Estimate Std. Error t value Pr(>|t|)    
# (Intercept)          0.41069    0.04573   8.980 1.88e-05 ***
# treatmentHigh_X_Low -0.04855    0.07468  -0.650   0.5338    
# treatmentLow_X_High -0.08406    0.08556  -0.982   0.3547    
# treatmentLow_X_Low  -0.20878    0.08556  -2.440   0.0406 *  
mod_means_contr <- emmeans::emmeans(object = Hurricane_mod,
                                    pairwise ~ "treatment",
                                    adjust = "tukey")
mod_means <- multcomp::cld(object = mod_means_contr$emmeans,
                           Letters = letters)
 # Arag emmean     SE df lower.CL upper.CL .group
 #    2  0.263 0.0433 11    0.168    0.358  a    
 #    4  0.287 0.0375 11    0.205    0.370  ab   
 #    3  0.454 0.0336 11    0.380    0.528    c  
 #    1  0.458 0.0433 11    0.363    0.554   bc  

summary(Hurricane_mod)
TukeyHSD(Hurricane_mod)
summary(
     aov(
       lm(
          Proportion_alive_ADJ ~
            Arag,
          data = (final_OM %>% # data %>%
                    dplyr::filter(population %in% 'Hurricane')  %>% 
                    dplyr::filter(!Proportion_alive_ADJ <0.18)) 
                    # dplyr::filter(!flow_cy_ID < 16))
         )
        )
       )

 scheirerRayHare(
          Proportion_alive_ADJ ~
            OA * Temperature,
          data = (final_OM %>% # data %>%
                    dplyr::filter(population %in% 'Hurricane')  %>% 
                    dplyr::filter(!Proportion_alive_ADJ <0.18))
 )
``` 